from ubuntu:14.04
maintainer "kat.mcivor@gmail.com"

run apt-get update
run apt-get install -y nginx supervisor

#nginx config
copy nginx/default /etc/nginx/sites-available/default
copy nginx/nginx.conf /etc/nginx/nginx.conf

#supervisored to keep it alive
copy nginx/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

expose 80

entrypoint /usr/bin/supervisord
